### PR TITLE
Cleaning up the code - Fixed hotkeys to not fire when mouselook is off a...

### PR DESCRIPTION
**Pull request by G33kDude**
...nd to hold down the key while you hold down the hotkey

### CODE REVIEW

**Comment by fabd** [comment]
Hello

Feel free to host your own version (ie. the fork), and perhaps update the README file to mention what your changes do?

I will not pull any commits or make significant changes because when it comes to Autohotkey almost everyone wants something different out of the script. So I think it is totally fine that you host your version of it. I'm happy enough to see it is forked and of benefit to someone. :)  (I mean, I don't think there can be "one" version of the script that would be contributed to in a meaningful way unless it was a really particularly complex AHK script, and this was mostly a Github Pages experiment).

That said, a (hopefully constructive) remark. Try to make the commit only about the actual changes. Cleaning up the code is highly subjective, especially in a Authotkey language that has a terrible syntax to begin with. But the main problem, is that you made those changes in the same commit than the functional changes, so because of all the "diffs" it is quite difficult for me to see what you changed. I recommend in this case to make a branch with the cleaned up code for your own use, and try and merge in the main branch only the functional changes that way when you commit the person receiving the pull request can better see what changed. Optionally if you want to commit also the cleaned up code, if they are in two separate steps it just makes it easier to see the functional changes.

In any case, thanks for sharing your changes. And please feel free to host the update version on here.

**Comment by G33kDude** [comment]
I wasn't aware of there being a github repo at the time I was modifying the
code. The only functional change I made was that the mouse rebinds now hold
the bound key while you hold the mouse button. That being said, you're
right about my pull request being terrible.

I disagree with your comment about AutoHotkey having terrible syntax, I'd
argue that there's just an overflow of inexperienced coders writing tons of
bad example code.

**Comment by fabd** [comment]
Ok. I haven't played RIFT in a while, out of curiosity could you give an example where you hold down the buttons? Maybe it is my character build that didn't use this type of action.

**Comment by G33kDude** [comment]
I've never played rift, I was modifying the code for someone else. They
said it was for crouching or something like that. I couldn't see a reason
that holding it could be bad, but then again I've never played rift.

**Pull request closed without merging**
